# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준) 형식
import numpy as np          

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [5]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array (ndarray)

In [6]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape

(dtype('float64'), (4,))

### Array shape

In [11]:
# Vector (1차원)
vec = np.array([1,4,5,8])
vec

array([1, 4, 5, 8])

In [12]:
vec.shape

(4,)

In [14]:
# Matrix(2차원)
matrix = np.array([[1,2,3,4], [5,6,7,8]])
print(matrix.shape)
matrix

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)     #수기로 다 입력 어려워서 이런 방식으로 사용
print(tensor)                   #평면2, 행3, 열4

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
tensor.shape

(2, 3, 4)

In [18]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 4), (2, 3, 4))

In [19]:
# .size : element의 개수
vec.size, matrix.size, tensor.size

(4, 8, 24)

In [20]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [25]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [ ]:
# reshape : element의 개수는 맞춰주면서(동일) array의 shape를 변경

In [22]:
matrix.shape

(2, 4)

In [23]:
matrix.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
matrix.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
# -1의 의미: numpy가 알아서 맞춰줌(단, size가 동일한 한도내에서)
# size를 기반으로 collum, row 개수 선정 (numpy가 알아서)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
matrix.reshape(4, -1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
matrix.reshape(4,-1).shape

(4, 2)

In [30]:
tensor.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
tensor.reshape(4, -1).shape

(4, 6)

In [32]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### flatten
- 다차원 array를 1차원 array로 변환

In [41]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## indexing & slicing

### indexing

In [43]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
matrix[0][1]

2

In [45]:
matrix[0,1]

2

In [46]:
tensor[1,1,2]

19

### slicing

In [48]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [50]:
# 5,6,7  9,10,11
b[1:3, 1: ]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [53]:
#1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [54]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))